/*
 *  Abuse - dark 2D side-scrolling platform game
 *  Copyright (c) 1995 Crack dot Com
 *  Copyright (c) 2005-2011 Sam Hocevar <sam@hocevar.net>
 *
 *  This software was released into the Public Domain. As with most public
 *  domain software, no warranty is made or implied by Crack dot Com, by
 *  Jonathan Clark, or by Sam Hocevar.
 */

#ifndef __EVENT_HPP_
#define __EVENT_HPP_

enum EventType
{
    EV_SPURIOUS,
    EV_MOUSE_MOVE,
    EV_MOUSE_BUTTON,
    EV_KEY,
    EV_KEYRELEASE,
    EV_TEXT_INPUT,
    EV_CLOSE_WINDOW,
    EV_MESSAGE,
};

constexpr int LEFT_BUTTON = 1;
constexpr int RIGHT_BUTTON = 2;
constexpr int MIDDLE_BUTTON = 4;

#include "keys.h"
#include "sprite.h"

#include <deque>
#include <string>
#include <utility>

class Jwindow;

void reset_input_sources();

class Event
{
  public:
    Event() = default;
    explicit Event(int id, void *data = nullptr) : type(EV_MESSAGE), message{id, data}
    {
    }

    EventType type = EV_SPURIOUS;
    ivec2 mouse_move = ivec2(0, 0);
    int mouse_button = 0;
    // Non-zero when an EV_KEY was generated by the mouse wheel. Positive
    // values move toward the beginning of a scrollbar, negative toward the end.
    int mouse_wheel = 0;
    int key = JK_NONE;
    std::string text;

    Jwindow *window = nullptr;
    struct
    {
        int id = 0;
        void *data = nullptr;
    } message;
};

class EventHandler
{
  public:
    EventHandler(image *screen, palette *pal);
    ~EventHandler();

    void Push(Event event)
    {
        m_events.push_back(std::move(event));
    }
    void PushMessage(int id, void *data = nullptr)
    {
        m_events.emplace_back(id, data);
    }

    bool IsPending();
    void Get(Event &ev);
    void flush_screen();

    void SetMouseShape(image *im, ivec2 center)
    {
        m_sprite->SetVisual(im, 1);
        m_center = center;
    }
    void SetMousePos(ivec2 pos);
    //AR
    ivec2 GetMousePos()
    {
        return this->m_pos;
    }
    void SetIgnoreWheelEvents(bool ignore)
    {
        m_ignore_wheel_events = ignore;
    }

  private:
    std::deque<Event> m_events;
    bool m_ignore_wheel_events = false;
    image *m_screen;

  protected:
    /* Mouse information */
    Sprite *m_sprite;
    ivec2 m_pos, m_center;
    int m_button;
};

#endif
