#!/bin/sh
set -eu

if [ "$(id -u)" -ne 0 ]; then
    echo "Run this installer as root (sudo ./systemd/install.sh)." >&2
    exit 1
fi

public_host="${1:-abusecoop.com}"
case "${public_host}" in
    ""|*[!A-Za-z0-9.-]*) echo "Invalid public host: ${public_host}" >&2; exit 1 ;;
esac

script_dir="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
target_dir=/opt/abuse-online/signaling
config_dir=/etc/abuse-online
caddy_file=/etc/caddy/Caddyfile
caddy_marker="# abuse-online:${public_host}"
caddy_end_marker="# abuse-online-end:${public_host}"

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs npm coturn
systemctl disable --now coturn.service 2>/dev/null || true

if ! getent passwd abuse-online >/dev/null; then
    useradd --system --home-dir /nonexistent --shell /usr/sbin/nologin abuse-online
fi

install -d -m 0755 /opt/abuse-online "${target_dir}" "${config_dir}"
cp -a "${script_dir}/signaling/package.json" "${script_dir}/signaling/package-lock.json" "${target_dir}/"
rm -rf "${target_dir}/src" "${target_dir}/node_modules"
cp -a "${script_dir}/signaling/src" "${target_dir}/src"
npm --prefix "${target_dir}" ci --omit=dev --ignore-scripts
chown -R abuse-online:abuse-online /opt/abuse-online

cat > "${config_dir}/signaling.env" <<EOF
HOST=127.0.0.1
PORT=8080
STUN_HOST=${public_host}
TRUST_PROXY=1
EOF
chmod 0644 "${config_dir}/signaling.env"
install -m 0644 "${script_dir}/stun/stun.conf" "${config_dir}/stun.conf"
install -m 0644 "${script_dir}/systemd/abuse-signaling.service" /etc/systemd/system/abuse-signaling.service
install -m 0644 "${script_dir}/systemd/abuse-stun.service" /etc/systemd/system/abuse-stun.service

candidate="$(mktemp)"
trap 'rm -f "${candidate}"' EXIT HUP INT TERM

# Remove blocks generated by earlier runs, including the previous domain.
awk '
    /^# abuse-online:[A-Za-z0-9.-]+$/ { skip = 1; next }
    /^# abuse-online-end:[A-Za-z0-9.-]+$/ { skip = 0; next }
    skip && $0 == "}" { skip = 0; next }
    !skip { print }
' "${caddy_file}" > "${candidate}"

cat >> "${candidate}" <<EOF

${caddy_marker}
${public_host} {
    @abuse_signaling path /health /v1/rooms/*
    reverse_proxy @abuse_signaling 127.0.0.1:8080

    header {
        Strict-Transport-Security "max-age=31536000"
        X-Content-Type-Options "nosniff"
        -Server
    }
}
${caddy_end_marker}
EOF
caddy fmt --overwrite "${candidate}"
caddy validate --config "${candidate}" --adapter caddyfile
cp "${caddy_file}" "${caddy_file}.before-abuse-online"
install -o root -g root -m 0644 "${candidate}" "${caddy_file}"
rm -f "${candidate}"
trap - EXIT HUP INT TERM

systemctl daemon-reload
systemctl enable abuse-signaling.service abuse-stun.service
systemctl restart abuse-signaling.service abuse-stun.service
systemctl reload caddy.service

attempt=0
until health="$(curl --fail --silent http://127.0.0.1:8080/health)"; do
    attempt=$((attempt + 1))
    if [ "${attempt}" -ge 10 ]; then
        echo "Signaling service did not become ready." >&2
        systemctl --no-pager --full status abuse-signaling.service >&2 || true
        exit 1
    fi
    sleep 1
done

printf '%s\n' "${health}"

attempt=0
until timeout 2s turnutils_stunclient 127.0.0.1 >/dev/null 2>&1; do
    attempt=$((attempt + 1))
    if [ "${attempt}" -ge 10 ]; then
        echo "STUN service did not become ready." >&2
        systemctl --no-pager --full status abuse-stun.service >&2 || true
        exit 1
    fi
    sleep 1
done

printf 'Installed Abuse signaling and STUN for %s\n' "${public_host}"
