set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_VERSION 23.6)

# The triplet and standalone SDL/game builds use the same toolchain.
if(VCPKG_TARGET_ARCHITECTURE STREQUAL "arm64" OR
        CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
    set(CMAKE_SYSTEM_PROCESSOR arm64)
    set(_abuse_osxcross_target arm64-apple-darwin23.6)
else()
    set(CMAKE_SYSTEM_PROCESSOR x86_64)
    set(_abuse_osxcross_target x86_64-apple-darwin23.6)
endif()
set(CMAKE_OSX_ARCHITECTURES "${CMAKE_SYSTEM_PROCESSOR}" CACHE STRING "")
set(CMAKE_OSX_DEPLOYMENT_TARGET "11.0" CACHE STRING "")
set(CMAKE_OSX_SYSROOT /osxcross/SDK/MacOSX14.5.sdk CACHE PATH "")
set(CMAKE_C_COMPILER /osxcross/bin/${_abuse_osxcross_target}-clang)
set(CMAKE_CXX_COMPILER /osxcross/bin/${_abuse_osxcross_target}-clang++)
set(CMAKE_INSTALL_NAME_TOOL /osxcross/bin/${_abuse_osxcross_target}-install_name_tool)
set(CMAKE_AR /osxcross/bin/${_abuse_osxcross_target}-ar)
set(CMAKE_RANLIB /osxcross/bin/${_abuse_osxcross_target}-ranlib)
set(CMAKE_STRIP /osxcross/bin/${_abuse_osxcross_target}-strip)
list(APPEND CMAKE_FIND_ROOT_PATH "${CMAKE_OSX_SYSROOT}" ${CMAKE_PREFIX_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES CMAKE_OSX_ARCHITECTURES)
