#ifndef FUNCS_H
#define FUNCS_H

enum class SysFunc
{
    Print,
    Car,
    Cdr,
    Length,
    List,
    Cons,
    Quote,
    Eq,
    Plus,
    Minus,
    If,
    Setf,
    SymbolList,
    Assoc,
    Null,
    Acons,
    Pairlis,
    Let,
    Defun,
    Atom,
    Not,
    And,
    Or,
    Progn,
    Equal,
    Concatenate,
    CharCode,
    CodeChar,
    Times,
    Slash,
    Cond,
    Select,
    Function,
    Mapcar,
    Funcall,
    GreaterThan,
    LessThan,
    TmpSpace,
    PermSpace,
    SymbolName,
    Trace,
    Untrace,
    Digstr,
    CompileFile,
    Abs,
    Min,
    Max,
    GreaterOrEqual,
    LessOrEqual,
    Backquote,
    Comma,
    Nth,
    ResizeTmp,
    ResizePerm,
    Cos,
    Sin,
    Atan2,
    Enum,
    Quit,
    Eval,
    Break,
    Mod,
    WriteProfile,
    Setq,
    For,
    OpenFile,
    Load,
    BitAnd,
    BitOr,
    BitXor,
    MakeArray,
    Aref,
    If1Progn,
    If2Progn,
    If12Progn,
    Eq0,
    Preport,
    Search,
    Elt,
    Listp,
    Numberp,
    Do,
    GarbageCollect,
    Schar,
    Symbolp,
    Num2Str,
    Nconc,
    First,
    Second,
    Third,
    Fourth,
    Fifth,
    Sixth,
    Seventh,
    Eighth,
    Ninth,
    Tenth,
    Substr,
    LocalLoad
};

enum class LispFunc
{
    GoState,
    WithObject,
    BMove, // returns true=unblocked, nil=block, or object
    Me,
    Bg,
    FindClosest,
    FindXClosest,
    FindXRange,
    AddObject, // type, x,y (type)
    FirstFocus,
    NextFocus,
    GetObject,
    GetLight,
    WithObjects,
    AddLight, // type, x, y, r1, r2, xshift, yshift
    FindEnemy, // exclude
    UserFun, // calls anobject's user function
    Time, // returns a fixed point (times and operation)
    Name, // returns current object's name (for debugin)
    FloatTick,
    FindObjectInArea, // x1, y1, x2, y2  type_list
    FindObjectInAngle, // start_angle end_angle type_list
    AddObjectAfter, // type, x,y (type)
    DefChar, // needs at least 2 parms
    SeeDist, // returns longest unblocked path from x1,y1,x2,y2
    Platform,
    LevelName,
    AntAi,
    SensorAi,
    DevDraw,
    TopAi,
    LaserUFun,
    TopUFun,
    PLaserUFun,
    PlayerRocketUFun,
    LSaberUFun,
    CopMover,
    LatterAi,
    WithObj0,
    Activated,
    TopDraw,
    BottomDraw,
    MoverAi,
    SGunAi,
    LastSavegameName,
    NextSavegameName,
    Argv,
    JoyStat, // xm ym b1 b2 b3
    MouseStat, // mx my b1 b2 b3
    MouseToGame, // pass in x,y -> x,y
    GameToMouse, // pass in x,y -> x,y
    GetMainFont,
    PlayerName,
    GetCwd,
    System,
    ConvertSlashes,
    GetDirectory, // path
    RespawnAi,
    ScoreDraw,
    ShowKills,
    MkPtr,
    Seq,
};

extern void initSysFuncs();
extern void initLispFuncs();

#endif // FUNCS_H
